import { Router } from 'express';
import authRoutes from './auth.routes.js';
import userRoutes from './users.routes.js';
import roleRoutes from './roles.routes.js';
import leadRoutes from './leads.routes.js';
import clientRoutes from './clients.routes.js';
import communicationRoutes from './communications.routes.js';
import projectRoutes from './projects.routes.js';
import employeeRoutes from './employees.routes.js';
import worklogRoutes from './worklogs.routes.js';
import revenueRoutes from './revenues.routes.js';
import paymentRoutes from './payments.routes.js';
import salaryRoutes from './salaries.routes.js';
import reimbursementRoutes from './reimbursements.routes.js';
import reportRoutes from './reports.routes.js';
import subscriptionRoutes from './subscriptions.routes.js';
import upcomingPaymentRoutes from './upcoming_payments.routes.js';
import dashboardRoutes from './dashboard.routes.js';
import reminderRoutes from './reminder.routes.js';

const router = Router();

router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/roles', roleRoutes);
router.use('/leads', leadRoutes);
router.use('/clients', clientRoutes);
router.use('/communications', communicationRoutes);
router.use('/projects', projectRoutes);
router.use('/employees', employeeRoutes);
router.use('/worklogs', worklogRoutes);
router.use('/revenues', revenueRoutes);
router.use('/payments', paymentRoutes);
router.use('/salaries', salaryRoutes);
router.use('/reimbursements', reimbursementRoutes);
router.use('/reports', reportRoutes);
router.use('/subscriptions', subscriptionRoutes);
router.use('/upcoming-payments', upcomingPaymentRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/reminders', reminderRoutes);

export default router;
